### ISSUE TITLE
cannot import wsgiserver

### ISSUE THREAD

**Issue by rkrejci** [cmoberg/bottle-yang-extractor-validator#4]
Hi, I'm not able to make the validator running locally. Probably due to missing some of the dependencies, but I'm out of ideas what next must be installed.

Running the `main.py` I'm getting the following error:
```
$ python --version
Python 2.7.6
$ sudo python ./bottle-yang-extractor-validator/main.py
Bottle v0.12.13 server starting up (using CherryPyServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.

Traceback (most recent call last):
  File "./main.py", line 253, in <module>
    run(server='cherrypy', host='0.0.0.0', port=port)
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.13-py2.7.egg/bottle.py", line 3127, in run
    server.run(app)
  File "/usr/local/lib/python2.7/dist-packages/bottle-0.12.13-py2.7.egg/bottle.py", line 2787, in run
    from cherrypy import wsgiserver
ImportError: cannot import name wsgiserver
```
I have tried it on Ubuntu 14.04 and 16.04 and on openSUSE with the same results. In all cases the `cherrypy-wsgiserver` (which seems to be connected with the error according to its name) is installed in version 0.1dev.

**Comment by cmoberg** [comment]
Hi Radek,

 How did you install the validator? All requirements including cherrypy are spelled out in setup.py and should be pulled in accordingly. So if installing by setup.py or pip, this should not happen :-)

**Comment by rkrejci** [comment]
I have used the `setup.py` and installation was ok:
```
$ sudo python2 ./setup.py install
root's password:
running install
running bdist_egg
running egg_info
writing requirements to bottle_yang_extractor_validator.egg-info/requires.txt
writing bottle_yang_extractor_validator.egg-info/PKG-INFO
writing top-level names to bottle_yang_extractor_validator.egg-info/top_level.txt
writing dependency_links to bottle_yang_extractor_validator.egg-info/dependency_links.txt
reading manifest file 'bottle_yang_extractor_validator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'bottle_yang_extractor_validator.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator
creating build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/views
copying build/lib/bottle-yang-extractor-validator/views/rest.tpl -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/views
copying build/lib/bottle-yang-extractor-validator/views/about.tpl -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/views
copying build/lib/bottle-yang-extractor-validator/views/result.tpl -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/views
copying build/lib/bottle-yang-extractor-validator/views/main.tpl -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/views
copying build/lib/bottle-yang-extractor-validator/main.py -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator
creating build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/static
creating build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/static/css
copying build/lib/bottle-yang-extractor-validator/static/css/pyangui.css -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/static/css
copying build/lib/bottle-yang-extractor-validator/__init__.py -> build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator
byte-compiling build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/main.py to main.pyc
byte-compiling build/bdist.linux-x86_64/egg/bottle-yang-extractor-validator/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying bottle_yang_extractor_validator.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bottle_yang_extractor_validator.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bottle_yang_extractor_validator.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bottle_yang_extractor_validator.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying bottle_yang_extractor_validator.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/bottle_yang_extractor_validator-0.3-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing bottle_yang_extractor_validator-0.3-py2.7.egg
Removing /usr/lib/python2.7/site-packages/bottle_yang_extractor_validator-0.3-py2.7.egg
Copying bottle_yang_extractor_validator-0.3-py2.7.egg to /usr/lib/python2.7/site-packages
bottle-yang-extractor-validator 0.3 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/bottle_yang_extractor_validator-0.3-py2.7.egg
Processing dependencies for bottle-yang-extractor-validator==0.3
Searching for CherryPy==10.2.1
Best match: CherryPy 10.2.1
Adding CherryPy 10.2.1 to easy-install.pth file
Installing cherryd script to /usr/bin

Using /usr/lib64/python2.7/site-packages
Searching for xym==0.3
Best match: xym 0.3
Processing xym-0.3-py2.7.egg
xym 0.3 is already the active version in easy-install.pth
Installing xym script to /usr/bin

Using /usr/lib/python2.7/site-packages/xym-0.3-py2.7.egg
Searching for bottle==0.12.13
Best match: bottle 0.12.13
Processing bottle-0.12.13-py2.7.egg
bottle 0.12.13 is already the active version in easy-install.pth
Installing bottle.py script to /usr/bin

Using /usr/lib/python2.7/site-packages/bottle-0.12.13-py2.7.egg
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for portend==1.8
Best match: portend 1.8
Adding portend 1.8 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for cheroot==5.3.0
Best match: cheroot 5.3.0
Adding cheroot 5.3.0 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Searching for requests==2.13.0
Best match: requests 2.13.0
Processing requests-2.13.0-py2.7.egg
requests 2.13.0 is already the active version in easy-install.pth

Using /usr/lib/python2.7/site-packages/requests-2.13.0-py2.7.egg
Searching for tempora==1.6.1
Best match: tempora 1.6.1
Adding tempora 1.6.1 to easy-install.pth file
Installing calc-prorate script to /usr/bin

Using /usr/lib/python2.7/site-packages
Searching for pytz==2015.2
Best match: pytz 2015.2
Adding pytz 2015.2 to easy-install.pth file

Using /usr/lib/python2.7/site-packages
Finished processing dependencies for bottle-yang-extractor-validator==0.3
```

Anyway, I'm getting the same error even when I try to install `autowsgiserver` which is based on `cherrypy`:
```
$ sudo pip install autowsgiserver
Collecting autowsgiserver
  Using cached autowsgiserver-0.1.26.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5oywplb0/autowsgiserver/setup.py", line 12, in <module>
        from autowsgiserver.info import NAME_SHORT, DESCR, VER_MAJOR, VER_MINOR
      File "/tmp/pip-build-5oywplb0/autowsgiserver/autowsgiserver/__init__.py", line 13, in <module>
        import cherrypy.wsgiserver
    ImportError: No module named 'cherrypy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5oywplb0/autowsgiserver/
```

so it seems to me that something is wrong with the `cherrypy` package. What distro are you using? I can try it in virtualbox.

**Comment by rkrejci** [comment]
Hi, it seems that CherryPy does not include `wsgiserver` in the latest versions -  cherrypy/cherrypy#1481. Possible solution is to use some older version of CherryPy:
```
pip install "cherrypy>=3.8.0,<9.0.0"
```

**Comment by cmoberg** [comment]
(Belated) thanks @rkrejci , I am updating the cherrypy requirement for the upcoming release.
